from app.repository.role import RoleRepository
from app.repository.user import UserRepository
from app.repository.patient import PatientRepository
from app.repository.country import CountryRepository
from app.repository.city import CityRepository
from app.repository.street import StreetRepository
from app.repository.building import BuildingRepository
from app.repository.hospital import HospitalRepository
from app.repository.diagnose import DiagnoseRepository
from app.repository.department import DepartmentRepository
from app.repository.cabinet import CabinetRepository
from app.repository.post import PostRepository
